---
galaxy_info:
  role_name: ocp4_workload_toolhive
  author: Red Hat, Wolfgang Kulhanek (wkulhane@redhat.com)
  description: |
    Set up the Toolhive operator on an OpenShift Cluster
  license: MIT
  min_ansible_version: "2.9"
  platforms:
  - linux
  galaxy_tags:
  - ocp
  - openshift
dependencies: []
